site_name: orc
site_url: https://allometric.github.io/orc/
repo_url: https://github.com/allometric/orc
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Schema:
      - Publication: publication.md
      - Model Families: families.md
  - Model kinds: kinds.md
  - API: api.md
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
